class LotinKirilConverter {
  static final Map<String, String> _latinToCyrillic = {
    "A": "А",
    "B": "Б",
    "D": "Д",
    "E": "Е",
    "F": "Ф",
    "G": "Г",
    "H": "Ҳ",
    "I": "И",
    "J": "Ж",
    "K": "К",
    "L": "Л",
    "M": "М",
    "N": "Н",
    "O": "О",
    "P": "П",
    "Q": "Қ",
    "R": "Р",
    "S": "С",
    "T": "Т",
    "U": "У",
    "V": "В",
    "X": "Х",
    "Y": "Й",
    "Z": "З",
    "O'": "Ў",
    "G'": "Ғ",
    "Sh": "Ш",
    "Ch": "Ч",
    "a": "а",
    "b": "б",
    "d": "д",
    "e": "е",
    "f": "ф",
    "g": "г",
    "h": "ҳ",
    "i": "и",
    "j": "ж",
    "k": "к",
    "l": "л",
    "m": "м",
    "n": "н",
    "o": "о",
    "p": "п",
    "q": "қ",
    "r": "р",
    "s": "с",
    "t": "т",
    "u": "у",
    "v": "в",
    "x": "х",
    "y": "й",
    "z": "з",
    "o'": "ў",
    "g'": "ғ",
    "sh": "ш",
    "ch": "ч"
  };

  static final Map<String, String> _cyrillicToLatin = {
    "А": "A",
    "Б": "B",
    "Д": "D",
    "Е": "E",
    "Ф": "F",
    "Г": "G",
    "Ҳ": "H",
    "И": "I",
    "Ж": "J",
    "К": "K",
    "Л": "L",
    "М": "M",
    "Н": "N",
    "О": "O",
    "П": "P",
    "Қ": "Q",
    "Р": "R",
    "С": "S",
    "Т": "T",
    "У": "U",
    "В": "V",
    "Х": "X",
    "Й": "Y",
    "З": "Z",
    "Ў": "O'",
    "Ғ": "G'",
    "Ш": "Sh",
    "Ч": "Ch",
    "а": "a",
    "б": "b",
    "д": "d",
    "е": "e",
    "ф": "f",
    "г": "g",
    "ҳ": "h",
    "и": "i",
    "ж": "j",
    "к": "k",
    "л": "l",
    "м": "m",
    "н": "n",
    "о": "o",
    "п": "p",
    "қ": "q",
    "р": "r",
    "с": "s",
    "т": "t",
    "у": "u",
    "в": "v",
    "х": "x",
    "й": "y",
    "з": "z",
    "ў": "o'",
    "ғ": "g'",
    "ш": "sh",
    "ч": "ch"
  };

  static String convert(String text, bool toCyrillic) {
    String result = "";
    Map<String, String> conversionMap =
        toCyrillic ? _latinToCyrillic : _cyrillicToLatin;

    text.split('').forEach((char) {
      if (conversionMap.containsKey(char)) {
        result += conversionMap[char]!;
      } else {
        result += char;
      }
    });

    return result;
  }
}
